version: "3.9"

services:
  mongo-database:
    image: mongo:latest
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
