server:
  port: 8081

spring:
  application:
    name: client-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/client_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
