server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongo-database:27017/product_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:9091/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
