server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db
      database: product_db
      auto-index-creation: true

application-version: 1.0

---
spring:
  config:
    activate:
      on-profile: test

  cloud:
    config:
      enabled: false

  data:
    mongodb:
      uri: mongodb://localhost:27018/product_test_db
      auto-index-creation: true
