server:
  port: 8084

spring:
  application:
    name: sale-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sale_db
      auto-index-creation: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/

client-service:
  url: http://localhost:8081
product-service:
  url: http://localhost:8082
stock-service:
  url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
