server:
  port: 8084

spring:
  application:
    name: sale-service
  data:
    mongodb:
      uri: mongodb://mongo-database:27017/sale_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:9091/eureka/

client-service:
  url: http://client-service:8081
product-service:
  url: http://product-service:8082
stock-service:
  url: http://stock-service:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
