server:
  port: 8083

spring:
  application:
    name: stock-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/stock_db
      auto-index-creation: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/

product-service:
  url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
