server:
  port: 8083

spring:
  application:
    name: stock-service
  data:
    mongodb:
      uri: mongodb://mongo-database:27017/stock_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:9091/eureka/

product-service:
  url: http://product-service:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

application-version: 1.0
