spring:
  application:
    name: stock-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 30
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
application-version: 1.0
